server:
   port: 10099
   tomcat:
      # 最大线程数
      max-threads: 100
      # 最小线程数
      min-spare-threads: 10
      # 队列长度
      accept-count: 50
      # 最大链接数
      max-connections: 1000
      #链接建立超时时间
      connection-timeout: 60000

spring:
   application:
      name: @pom.artifactId@
   zipkin:
     base-url: http://docker.for.mac.host.internal:9411/
     sleuth:
       sampler:
         probability: 1.0
   datasource:
      master:
         username: root
         password:
         jdbc-url: jdbc:mysql://docker.for.mac.host.internal:3306/giant_user?autoReconnect=true&failOverReadOnly=false&useUnicode=true&queryTimeout=2400&characterEncoding=utf-8&allowMultiQueries=true
         driver-class-name: com.mysql.cj.jdbc.Driver
         type: com.zaxxer.hikari.HikariDataSource
         hikari:
            minimum-idle: 10
            maximum-pool-size: 50
            auto-commit: true
            idle-timeout: 30000
            max-lifetime: 1800000
            connection-timeout: 30000
            connection-test-query: SELECT 1
      slave:
         username: root
         password:
         jdbc-url: jdbc:mysql://docker.for.mac.host.internal:3306/giant_bike?autoReconnect=true&failOverReadOnly=false&useUnicode=true&queryTimeout=2400&characterEncoding=utf-8&allowMultiQueries=true
         driver-class-name: com.mysql.cj.jdbc.Driver
         type: com.zaxxer.hikari.HikariDataSource
         hikari:
            minimum-idle: 10
            maximum-pool-size: 50
            auto-commit: true
            idle-timeout: 30000
            max-lifetime: 1800000
            connection-timeout: 30000
            connection-test-query: SELECT 1

eureka:
   client:
      serviceUrl:
         defaultZone: http://docker.for.mac.host.internal:10100/eureka/
      register-with-eureka: true
      fetch-registry: true
   instance:
      prefer-ip-address: true
      instance-id: ${spring.cloud.client.ip-address}:${server.port}

mybatis:
   mapper-locations: classpath:/mapper/*.xml

app:
   id: @pom.artifactId@
   
apollo:
   meta: http://docker.for.mac.host.internal:8080